### PR TITLE
Root path (and reverse proxy) fixes

### PR DESCRIPTION
**Pull request by avillar**

### CODE REVIEW

**Comment by avillar** [comment]
A few tests are failing, which I'm not surprised about. Looks like they're for OGC API Features stuff.

**Comment by recalcitrantsupplant** [comment]
Thanks Alejandro I'll try get to this soon

**Review by recalcitrantsupplant — APPROVED** [review]
I've set proxy headers to False by default - aware we previously had it set to True, so you'll need to explicitly enable it. Have set the default forwarded_allow_ips to 127.0.0.1 in both the Dockerfile and config.py/settings.

I don't usually touch these settings - let me know if any concerns re. the above, if not will merge tomorrow.

**Comment by avillar** [comment]
`--proxy-headers` needs to be a flag (just pushed a fix), but other than that I think it works :)

**Pull request merged**
