### PR TITLE
SPARQL endpoint opt in

### PR DESCRIPTION
**Pull request by recalcitrantsupplant**
Makes the SPARQL endpoint opt in using the enable_sparql_endpoint variable in settings; defaulted to False.

### CODE REVIEW

**Review by lalewis1 — DISMISSED** [review]
yeah looks good, thanks :)

**Comment by lalewis1** [comment]
@recalcitrantsupplant I can't request your review as this is your PR but if you 'approve' the changes from my commit then I will approve the PR.

**Comment by recalcitrantsupplant** [comment]
thanks for the fix, I've changed it from "1" to "true" just for clarity

**Comment by recalcitrantsupplant** [comment]
Can't see an option to request your review.. has it changed since I pushed another commit?

**Comment by lalewis1** [comment]
Yeah im not sure how that works. i was hoping to 'suggest  changes' but i needed to change a file that wasn't part of the PR so I had to push a new commit.

anyway, im happy with it so I will approve.

**Review by lalewis1 — APPROVED** [review]
all good thanks

**Pull request merged**
