### PR TITLE
OGC Features queryables bugfix + cleaner curie generation

### PR DESCRIPTION
**Pull request by recalcitrantsupplant**
1. OGC Features bugfix for auto generated queryables.
2. Add upfront validation of curie -> URI and raise URI not found exception if appropriate. 
3. Add special characters to those excluded from CURIE generation: "aeiou!@#$%^&*()_+-=,."

### CODE REVIEW

**Comment by lalewis1** [comment]
Looks good, seems to work fine.

However, I am still getting a parser issue in prez-ui, even
without any prefixes with '.'s in them.

Will add to the relevant issue thread.

probably safer not to have any of those characters in the prefixes anyway.

**Review by lalewis1 — APPROVED** [review]
thanks. looks good

**Comment by recalcitrantsupplant** [comment]
good catch, yes I think you're right. We'll probably end up with the ns[1-9] type auto generated prefixes from RDFLib in a lot of cases "2.0" -> "" -> ns1 etc.

**Comment by lalewis1** [comment]
@recalcitrantsupplant , I have implemented the prefix fix. you'll see that i am hashing the uri to get a prefix. I wonder if we could also do this in place of 'ns1' 'ns2' style prefixes? did you say that was an rdflib thing? or is that something we can control from Prez?

**Review by lalewis1 — APPROVED** [review]

**Pull request merged**
